USE CODEGNAN;
DROP TABLE STUDENT123;
CREATE TABLE STUDENT123(
   ID INT ,
   SNAME VARCHAR(50)
);

INSERT INTO STUDENT123 VALUES(1,"FARHA 1"),(2,"FARHA 2"),(3,"FARHA 3"),(4,"FARHA 4");
SELECT* FROM STUDENT123;
CREATE TABLE COURSE123(
    CID INT,
    NAME VARCHAR(50)
);

INSERT INTO COURSE123 VALUES(1,"ECE"),(2,"EEE"),(1,"CSE"),(3,"ABC");
SELECT * FROM COURSE123;

-- INNERJOIN

SELECT ID,SNAME FROM STUDENT123
INNER JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID;

-- LEFT JOIN
SELECT ID,SNAME FROM STUDENT123
LEFT JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID;

-- RIGHT JOIN
SELECT ID,SNAME FROM STUDENT123
RIGHT JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID;

-- FULL OUTER JOIN
SELECT ID,SNAME FROM STUDENT123
LEFT JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID
UNION
SELECT ID,SNAME FROM STUDENT123
RIGHT JOIN COURSE123
ON STUDENT123.ID = COURSE123.CID;

-- SELF JOIN
CREATE TABLE CLR(
 COLOUR1 varchar(10),
 CNAME VARCHAR(10),
 COLOUR2 VARCHAR(10)
 );
 
 INSERT INTO CLR VALUES("BLUE","JOHN","RED"),("GREEN","ALEX","BLUE"),("RED","SIMON","GREEN");
 
 SELECT * FROM CLR;
 -- SELF
 SELECT B.CNAME AS SECRET_SANTA,A.CNAME AS NAME
 FROM CLR AS A,CLR AS B
 WHERE A.COLOUR1 = B.COLOUR2;
 
 -- CROSS
 CREATE TABLE HAIRSTYLE(
 NAME VARCHAR(100)
 );
 
 INSERT INTO HAIRSTYLE VALUES("STRAIGHT"),("CURLY");
 
 SELECT * FROM HAIRSTYLE;
 
 CREATE TABLE HAIRTYPE(
 UNAME VARCHAR(3)
 );
 
 INSERT INTO HAIRTYPE VALUES("A"),("B"),("C"),("D");
 
 SELECT * FROM HAIRTYPE;
 
 SELECT UNAME,NAMEE FROM HAIRTYPE
 CROSS JOIN 
 HAIRSTYLE ;
 
 SELECT UNAME,NAMEE FROM HAIRTYPE 
 CROSS JOIN 
 HAIRSTYLE
 LIMIT 5;

