USE CODEGNAN;

CREATE TABLE USERS (USERID INT PRIMARY KEY NOT  NULL, NAME VARCHAR(100) NOT NULL, AGE INT DEFAULT 0);

CREATE TABLE ORDERS (
     ORDERID INT PRIMARY KEY, 
     PRODUCTNAME VARCHAR(100),
     PRICE INT DEFAULT 0,
     UID INT NOT NULL,
     FOREIGN KEY (UID) REFERENCES USERS(USERID)
);

DESC USERS;

DESC ORDERS;

INSERT INTO USERS VALUES(1, "FARHA", 15);

SELECT * FROM USERS;

SELECT * FROM ORDERS;

INSERT INTO ORDERS VALUES(101, "SOAP", 50, 1);

INSERT INTO ORDERS VALUES(102, "TOOTH BRUSH", 100, 1);

INSERT INTO ORDERS VALUES(103, "BATH SOAP", 150, 1);




CREATE TABLE CATEGORIES(CATEGORYID INT PRIMARY KEY auto_increment, NAME VARCHAR(50) NOT NULL);

DESC CATEGORIES;

DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
PRODUCT_ID INT PRIMARY KEY,
CATEGORYID INT NOT NULL,
NAME VARCHAR(100) NOT NULL,
PRICE int NOT NULL,
foreign key(CATEGORYID) REFERENCES CATEGORIES(CATEGORYID)
); 
DESC PRODUCT;

INSERT INTO CATEGORIES VALUES(201, "AMAZON");

INSERT INTO CATEGORIES VALUES(202, "FLIPKART");

INSERT INTO CATEGORIES VALUES(203, "MYNTRA");

SELECT * FROM CATEGORIES;

SELECT * FROM PRODUCT;

INSERT INTO PRODUCT VALUES(001, 202, "SONOTA", 1500);  -----CATOGERYID SHOULD BE SAME AS IN THE PREVIOUS TABLE

INSERT INTO PRODUCT VALUES(002, 202, "FASTRACK", 2000);

INSERT INTO PRODUCT VALUES(003, 203, "TITAN", 3000);


