-- ONE TO ONE RELATIONSHOIP EAMPLE:

CREATE TABLE CATEGORIES(CATEGORYID INT PRIMARY KEY auto_increment, NAME VARCHAR(50) NOT NULL);

DESC CATEGORIES;

DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
PRODUCT_ID INT PRIMARY KEY,
CATEGORYID INT NOT NULL,
NAME VARCHAR(100) NOT NULL,
PRICE int NOT NULL,
foreign key(CATEGORYID) REFERENCES CATEGORIES(CATEGORYID)
); 
DESC PRODUCT;

INSERT INTO CATEGORIES VALUES(201, "AMAZON");

INSERT INTO CATEGORIES VALUES(202, "FLIPKART");

INSERT INTO CATEGORIES VALUES(203, "MYNTRA");

-- 2- EXAMPLE

CREATE DATABASE LIBRARY;

USE LIBRARY;

CREATE TABLE AUTHORS(AUTHOR_ID INT PRIMARY KEY, NAME VARCHAR(100) NOT NULL);

DESC AUTHORS;


CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY,
NAME VARCHAR (100),
AUTHOR_ID INT NOT NULL,
FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

DESC BOOKS;

SELECT * FROM AUTHORS;
SELECT * FROM BOOKS;

INSERT INTO AUTHORS VALUES(1, "ABRAHAM LINCON");
INSERT INTO AUTHORS VALUES(2, "MARTIN");

INSERT INTO BOOKS VALUES(01, "THE ABC MURDERS", 1);
INSERT INTO BOOKS VALUES(02, "THE ADVENTURE OF TOM MAYERS", 2);
INSERT INTO BOOKS VALUES(03, "THE MURDERS", 3);

-- ONE TO MANY RELATIONSHIP(1ST EXAMPLE)

CREATE TABLE AUTHORS(AUTHOR_ID INT PRIMARY KEY, NAME VARCHAR(100) NOT NULL);

DESC AUTHORS;

DROP TABLE BOOKS;

CREATE TABLE BOOKS(
BOOK_ID INT PRIMARY KEY,
NAME VARCHAR (100),
AUTHOR_ID INT NOT NULL,
FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

DESC BOOKS;

SELECT * FROM AUTHORS;

INSERT INTO AUTHORS(author_id, name) VALUES(1, "ABRAHAM LINCON"),(2, "MARTIN");

INSERT INTO BOOKS(book_id, NAME, author_id)  VALUES (1, "THE ABC MURDERS", 1),
(2, "THE HARRY POTTER", 1),
(3, "THE ADVENTURE", 2),
(4, "THE ADVENTURE OF TOM MAYERS", 2),(5, "THE MURDERS", 3);
